"""add core spatial schedule capture tables

Revision ID: 05467aeda70a
Revises: 20260821_0001
Create Date: 2026-08-21 17:06:38.277065
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "05467aeda70a"
down_revision: str | None = "20260821_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "floors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("level_index", sa.Integer(), nullable=False),
        sa.Column("elevation_m", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_floors_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_floors")),
        sa.UniqueConstraint("project_id", "level_index", name="uq_floor_project_level"),
        sa.UniqueConstraint("project_id", "name", name="uq_floor_project_name"),
    )
    op.create_index(op.f("ix_floors_project_id"), "floors", ["project_id"], unique=False)
    op.create_table(
        "media_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("media_kind", sa.String(length=30), nullable=False),
        sa.Column("bucket", sa.String(length=100), nullable=False),
        sa.Column("object_key", sa.String(length=1000), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=True),
        sa.Column("content_type", sa.String(length=150), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("upload_status", sa.String(length=20), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_media_files_nonnegative_size")),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_media_files_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_media_files_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_files")),
        sa.UniqueConstraint("bucket", "object_key", name="uq_media_object"),
    )
    op.create_index(op.f("ix_media_files_project_id"), "media_files", ["project_id"], unique=False)
    op.create_table(
        "captures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source_video_id", sa.Uuid(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("captured_by_text", sa.String(length=200), nullable=True),
        sa.Column("start_floor_id", sa.Uuid(), nullable=False),
        sa.Column("start_x", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("start_y", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "start_x >= 0 AND start_x <= 1 AND start_y >= 0 AND start_y <= 1",
            name=op.f("ck_captures_normalized_start"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_captures_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_captures_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_video_id"],
            ["media_files.id"],
            name=op.f("fk_captures_source_video_id_media_files"),
        ),
        sa.ForeignKeyConstraint(
            ["start_floor_id"], ["floors.id"], name=op.f("fk_captures_start_floor_id_floors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_captures")),
        sa.UniqueConstraint("source_video_id", name=op.f("uq_captures_source_video_id")),
    )
    op.create_index(op.f("ix_captures_captured_at"), "captures", ["captured_at"], unique=False)
    op.create_index(op.f("ix_captures_project_id"), "captures", ["project_id"], unique=False)
    op.create_table(
        "rooms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("floor_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("polygon_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["floor_id"], ["floors.id"], name=op.f("fk_rooms_floor_id_floors"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rooms")),
        sa.UniqueConstraint("floor_id", "name", name="uq_room_floor_name"),
    )
    op.create_index(op.f("ix_rooms_floor_id"), "rooms", ["floor_id"], unique=False)
    op.create_table(
        "schedule_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_media_file_id", sa.Uuid(), nullable=True),
        sa.Column("is_baseline", sa.Boolean(), nullable=False),
        sa.Column("imported_by_id", sa.Uuid(), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "row_count >= 0", name=op.f("ck_schedule_versions_nonnegative_row_count")
        ),
        sa.ForeignKeyConstraint(
            ["imported_by_id"], ["users.id"], name=op.f("fk_schedule_versions_imported_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_schedule_versions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_media_file_id"],
            ["media_files.id"],
            name=op.f("fk_schedule_versions_source_media_file_id_media_files"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_versions")),
        sa.UniqueConstraint("project_id", "checksum", name="uq_schedule_project_checksum"),
        sa.UniqueConstraint("project_id", "version_no", name="uq_schedule_project_version"),
    )
    op.create_index(
        op.f("ix_schedule_versions_project_id"), "schedule_versions", ["project_id"], unique=False
    )
    op.create_table(
        "sheets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("floor_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sheet_type", sa.String(length=30), nullable=False),
        sa.Column("source_media_file_id", sa.Uuid(), nullable=True),
        sa.Column("preview_media_file_id", sa.Uuid(), nullable=True),
        sa.Column("width_px", sa.Integer(), nullable=True),
        sa.Column("height_px", sa.Integer(), nullable=True),
        sa.Column("scale_m_per_normalized_unit", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["floor_id"], ["floors.id"], name=op.f("fk_sheets_floor_id_floors"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["preview_media_file_id"],
            ["media_files.id"],
            name=op.f("fk_sheets_preview_media_file_id_media_files"),
        ),
        sa.ForeignKeyConstraint(
            ["source_media_file_id"],
            ["media_files.id"],
            name=op.f("fk_sheets_source_media_file_id_media_files"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sheets")),
    )
    op.create_index(op.f("ix_sheets_floor_id"), "sheets", ["floor_id"], unique=False)
    op.create_table(
        "activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("schedule_version_id", sa.Uuid(), nullable=False),
        sa.Column("parent_activity_id", sa.Uuid(), nullable=True),
        sa.Column("wbs", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("planned_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("planned_finish", sa.DateTime(timezone=True), nullable=False),
        sa.Column("percent_complete_source", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("is_summary", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("source_row_no", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "percent_complete_source IS NULL OR "
            "(percent_complete_source >= 0 AND percent_complete_source <= 100)",
            name=op.f("ck_activities_valid_percent_complete"),
        ),
        sa.CheckConstraint(
            "planned_finish >= planned_start", name=op.f("ck_activities_valid_dates")
        ),
        sa.ForeignKeyConstraint(
            ["parent_activity_id"],
            ["activities.id"],
            name=op.f("fk_activities_parent_activity_id_activities"),
        ),
        sa.ForeignKeyConstraint(
            ["schedule_version_id"],
            ["schedule_versions.id"],
            name=op.f("fk_activities_schedule_version_id_schedule_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
        sa.UniqueConstraint("schedule_version_id", "wbs", name="uq_activity_schedule_wbs"),
    )
    op.create_index(
        op.f("ix_activities_schedule_version_id"),
        "activities",
        ["schedule_version_id"],
        unique=False,
    )
    op.create_table(
        "beam_segments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sheet_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("beam_type", sa.String(length=50), nullable=True),
        sa.Column("start_x", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("start_y", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("end_x", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("end_y", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("length_m", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length_m IS NULL OR length_m > 0", name=op.f("ck_beam_segments_positive_length")
        ),
        sa.CheckConstraint(
            "start_x >= 0 AND start_x <= 1 AND start_y >= 0 AND start_y <= 1 "
            "AND end_x >= 0 AND end_x <= 1 AND end_y >= 0 AND end_y <= 1",
            name=op.f("ck_beam_segments_normalized_coordinates"),
        ),
        sa.ForeignKeyConstraint(
            ["sheet_id"],
            ["sheets.id"],
            name=op.f("fk_beam_segments_sheet_id_sheets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_beam_segments")),
        sa.UniqueConstraint("sheet_id", "code", name="uq_beam_segment_code"),
    )
    op.create_index(op.f("ix_beam_segments_sheet_id"), "beam_segments", ["sheet_id"], unique=False)
    op.create_table(
        "grid_axes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sheet_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=30), nullable=False),
        sa.Column("axis_group", sa.String(length=20), nullable=False),
        sa.Column("start_x", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("start_y", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("end_x", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("end_y", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.CheckConstraint(
            "start_x >= 0 AND start_x <= 1 AND start_y >= 0 AND start_y <= 1 "
            "AND end_x >= 0 AND end_x <= 1 AND end_y >= 0 AND end_y <= 1",
            name=op.f("ck_grid_axes_normalized_coordinates"),
        ),
        sa.ForeignKeyConstraint(
            ["sheet_id"],
            ["sheets.id"],
            name=op.f("fk_grid_axes_sheet_id_sheets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grid_axes")),
        sa.UniqueConstraint("sheet_id", "axis_group", "label", name="uq_grid_axis_label"),
    )
    op.create_index(op.f("ix_grid_axes_sheet_id"), "grid_axes", ["sheet_id"], unique=False)
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("capture_id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("progress_percent", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("pipeline_version", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("attempt_no >= 1", name=op.f("ck_processing_jobs_positive_attempt")),
        sa.CheckConstraint(
            "progress_percent >= 0 AND progress_percent <= 100",
            name=op.f("ck_processing_jobs_valid_progress"),
        ),
        sa.ForeignKeyConstraint(
            ["capture_id"],
            ["captures.id"],
            name=op.f("fk_processing_jobs_capture_id_captures"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
        sa.UniqueConstraint("idempotency_key", name="uq_processing_job_idempotency"),
    )
    op.create_index(
        op.f("ix_processing_jobs_capture_id"), "processing_jobs", ["capture_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processing_jobs_capture_id"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index(op.f("ix_grid_axes_sheet_id"), table_name="grid_axes")
    op.drop_table("grid_axes")
    op.drop_index(op.f("ix_beam_segments_sheet_id"), table_name="beam_segments")
    op.drop_table("beam_segments")
    op.drop_index(op.f("ix_activities_schedule_version_id"), table_name="activities")
    op.drop_table("activities")
    op.drop_index(op.f("ix_sheets_floor_id"), table_name="sheets")
    op.drop_table("sheets")
    op.drop_index(op.f("ix_schedule_versions_project_id"), table_name="schedule_versions")
    op.drop_table("schedule_versions")
    op.drop_index(op.f("ix_rooms_floor_id"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_index(op.f("ix_captures_project_id"), table_name="captures")
    op.drop_index(op.f("ix_captures_captured_at"), table_name="captures")
    op.drop_table("captures")
    op.drop_index(op.f("ix_media_files_project_id"), table_name="media_files")
    op.drop_table("media_files")
    op.drop_index(op.f("ix_floors_project_id"), table_name="floors")
    op.drop_table("floors")
    # ### end Alembic commands ###
