"""add immutable human progress entries

Revision ID: 1d8a918059e3
Revises: 05467aeda70a
Create Date: 2026-08-21 17:26:01.976224
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1d8a918059e3"
down_revision: str | None = "05467aeda70a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "human_progress_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("capture_id", sa.Uuid(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("progress_percent", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("entered_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "progress_percent >= 0 AND progress_percent <= 100",
            name=op.f("ck_human_progress_entries_valid_progress"),
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_human_progress_entries_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["capture_id"],
            ["captures.id"],
            name=op.f("fk_human_progress_entries_capture_id_captures"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["entered_by_id"],
            ["users.id"],
            name=op.f("fk_human_progress_entries_entered_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_human_progress_entries_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_progress_entries")),
    )
    op.create_index(
        op.f("ix_human_progress_entries_activity_id"),
        "human_progress_entries",
        ["activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_human_progress_entries_capture_id"),
        "human_progress_entries",
        ["capture_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_human_progress_entries_entered_by_id"),
        "human_progress_entries",
        ["entered_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_human_progress_entries_observed_at"),
        "human_progress_entries",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_human_progress_entries_project_id"),
        "human_progress_entries",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_human_progress_entries_project_id"), table_name="human_progress_entries")
    op.drop_index(
        op.f("ix_human_progress_entries_observed_at"), table_name="human_progress_entries"
    )
    op.drop_index(
        op.f("ix_human_progress_entries_entered_by_id"), table_name="human_progress_entries"
    )
    op.drop_index(op.f("ix_human_progress_entries_capture_id"), table_name="human_progress_entries")
    op.drop_index(
        op.f("ix_human_progress_entries_activity_id"), table_name="human_progress_entries"
    )
    op.drop_table("human_progress_entries")
    # ### end Alembic commands ###
