"""add resumable multipart uploads

Revision ID: 676a09544382
Revises: 1d8a918059e3
Create Date: 2026-08-21 17:48:42.355801
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "676a09544382"
down_revision: str | None = "1d8a918059e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "multipart_upload_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("media_file_id", sa.Uuid(), nullable=False),
        sa.Column("provider_upload_id", sa.String(length=1000), nullable=False),
        sa.Column("part_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "part_size_bytes >= 5242880",
            name=op.f("ck_multipart_upload_sessions_valid_part_size"),
        ),
        sa.ForeignKeyConstraint(
            ["media_file_id"],
            ["media_files.id"],
            name=op.f("fk_multipart_upload_sessions_media_file_id_media_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_multipart_upload_sessions")),
        sa.UniqueConstraint(
            "media_file_id", name=op.f("uq_multipart_upload_sessions_media_file_id")
        ),
        sa.UniqueConstraint(
            "provider_upload_id",
            name=op.f("uq_multipart_upload_sessions_provider_upload_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("multipart_upload_sessions")
    # ### end Alembic commands ###
