"""add video metadata and keyframes

Revision ID: 87a7c87dbddb
Revises: 676a09544382
Create Date: 2026-08-21 18:02:18.043927
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "87a7c87dbddb"
down_revision: str | None = "676a09544382"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_metadata",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("media_file_id", sa.Uuid(), nullable=False),
        sa.Column("format_name", sa.String(length=100), nullable=False),
        sa.Column("codec_name", sa.String(length=100), nullable=False),
        sa.Column("duration_ms", sa.BigInteger(), nullable=False),
        sa.Column("width_px", sa.Integer(), nullable=False),
        sa.Column("height_px", sa.Integer(), nullable=False),
        sa.Column("fps", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("is_equirectangular", sa.Boolean(), nullable=False),
        sa.Column("ffprobe_json", sa.Text(), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("duration_ms > 0", name=op.f("ck_video_metadata_positive_duration")),
        sa.CheckConstraint(
            "width_px > 0 AND height_px > 0", name=op.f("ck_video_metadata_positive_dimensions")
        ),
        sa.ForeignKeyConstraint(
            ["media_file_id"],
            ["media_files.id"],
            name=op.f("fk_video_metadata_media_file_id_media_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_metadata")),
        sa.UniqueConstraint("media_file_id", name=op.f("uq_video_metadata_media_file_id")),
    )
    op.create_table(
        "keyframes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("capture_id", sa.Uuid(), nullable=False),
        sa.Column("media_file_id", sa.Uuid(), nullable=False),
        sa.Column("frame_index", sa.Integer(), nullable=False),
        sa.Column("timestamp_ms", sa.BigInteger(), nullable=False),
        sa.Column("quality_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("frame_index >= 0", name=op.f("ck_keyframes_nonnegative_frame_index")),
        sa.CheckConstraint("timestamp_ms >= 0", name=op.f("ck_keyframes_nonnegative_timestamp")),
        sa.ForeignKeyConstraint(
            ["capture_id"],
            ["captures.id"],
            name=op.f("fk_keyframes_capture_id_captures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["media_file_id"],
            ["media_files.id"],
            name=op.f("fk_keyframes_media_file_id_media_files"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_keyframes")),
        sa.UniqueConstraint("capture_id", "frame_index", name="uq_keyframe_capture_frame"),
        sa.UniqueConstraint("capture_id", "timestamp_ms", name="uq_keyframe_capture_timestamp"),
    )
    op.create_index(op.f("ix_keyframes_capture_id"), "keyframes", ["capture_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_keyframes_capture_id"), table_name="keyframes")
    op.drop_table("keyframes")
    op.drop_table("video_metadata")
    # ### end Alembic commands ###
